### ISSUE TITLE
spaghetti on dog head

### ISSUE THREAD

**Issue by qiugai** [Salisbury-University/robot-weed-killer#10]
![1596048433135](https://user-images.githubusercontent.com/95944392/207763527-1e34d6cf-cec0-4fe8-9895-a0d11dffb54c.jpg)

**Comment by ZM009** [comment]
They can see these issues lol

**Comment by qiugai** [comment]
good

**Comment by ZM009** [comment]
Just take the spaghetti off the dawg's head

**Comment by qiugai** [comment]
smart, this is why we pay you the big bucks
