### ISSUE TITLE
Joystick Animation Glitching

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#12]
## Expected Behavior

Joystick should run smoothly at ~30-40 frames per second when connected via bluetooth, while sending bt messages to the Arduino.

## Actual Behavior

When connected to bluetooth and sending navigation messages, the joystick animation stutters and glitches back and forth.

## Steps to Reproduce Behavior

* Launch app on smartphone
* Connect to the Arduino via the bluetooth menu
* Move joystick around while connected

##### Adding a Duration object to the Joystick View(?)
```
interval: Duration* ()
```

**Comment by ZM009** [comment]
Will possibly fix at a later date; No solution at the moment.

**Comment by qiugai** [comment]
Will not be fixed. More than likely phasing out joystick and focusing more on automated control first. (Slim chance to reopen later)
