### ISSUE TITLE
Resize Webview to fit screen

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#17]
### Current Feature

The webview is contained in the middle of the screen at a fixed size, when it is set to on and set to off.

### Updated Feature

Ideally, the container of the webview will be expanded to the entire screen to allow the webview to dynamically fit any android screen regardless of dimensions.

**Comment by AdultVaccinationsLES** [comment]
Webview container dynamically fills the screen, so should be the same across devices. Additional widgets have yet to be positioned. 


![Image](https://user-images.githubusercontent.com/107266441/219070780-fc737448-2efd-428d-a3fa-1ea1ae0fbfea.png)
