### ISSUE TITLE
Pixel Overflow on Screen Expansion

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#19]
## Expected Behavior

When the webview is expanded to the entire screen of a phone, the buttons to control the robot manually should stay on top of the view, allowing the user to see the robot's camera view while still controlling its movement.

## Actual Behavior

When the screen is resized beyond certain dimensions (w x h), the joystick and other relevant buttons are pushed off the screen which causes a pixel overflow, and a while portion of the screen. 

------
#### Possible Solution

Row containing buttons may need to be expanded or redone from the ground up.

**Comment by AdultVaccinationsLES** [comment]
flutter_webview doesn't allow widget stacking, so switching to webviewx might be our best option. Webviewx allows widget stacking, but will require us to upgrade our current version of flutter which resolves the overflow issue on the view screen but will require updating some dependencies and reworking some of the code.

**Comment by ZM009** [comment]
@evHitch i'll checkout webviewx

**Comment by ZM009** [comment]
WebviewX has been implemented, and the buttons are able to be stacked on top of the view.

**Comment by AdultVaccinationsLES** [comment]
Implemented WebviewX & resolved the overflow issue. I'll be fixing the layout of the page next. 


![Image](https://user-images.githubusercontent.com/107266441/219069469-044e5d50-bc86-4ad7-bdfc-3f8a77e15a80.png)

**Comment by ZM009** [comment]
Design needs work as it is rudimentary, otherwise approved.

**Comment by nickkrisulevicz** [comment]
Issue has been fixed. Looks good.
