### ISSUE TITLE
Budget Consulting with Franchi

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#20]
### Plan:

Meeting to setup a budget for a new robot body design to allow the robot to drive smoothly and operate in rougher terrain.

**Comment by nickkrisulevicz** [comment]
Awaiting response from client for meeting time

**Comment by nickkrisulevicz** [comment]
Done - client said budget will be given if necessary, but there is no set amount. Preferably spend as little as possible

**Comment by ZM009** [comment]
Meeting finished for now, given clear goals before setting a defined budget. 👍
