### ISSUE TITLE
Alternative Power Source

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#22]
### Current Hardware 

The robot is chassis is powered by four 9V batteries, which provide inefficient amperage and are prone to dying rapidly after prolonged use of the robot's motors.

### Future Goal

Find a rechargeable battery to power the motors and BT module with sufficient amperage and voltage output.

**Comment by dakers01** [comment]
![DF8EEA74-9460-42B9-86CF-0B40D55C868F](https://user-images.githubusercontent.com/103211954/217568221-d39b78eb-459c-4786-ae7e-d0f7b6a0d2d8.jpeg)
New power source recieved, one will replace the current 9v batteries, the other will be a backup able to be switched out when needed.

**Comment by ZM009** [comment]
Amperage should be strong enough too so it isn't useless below 6V of charge. LGTM
