### ISSUE TITLE
Plan setup of server to receive / process ESP32 footage

### ISSUE THREAD

**Issue by qiugai** [Salisbury-University/robot-weed-killer#24]
In order to receive the live camera feed for image processing to allow the robot to move autonomously, there must be a server to perform this processing. 

We must add a new node into the map in order to process image data, along with sending communications to the Android phone to instruct the robot where to move, and read whether to activate or pause autonomous navigation.

**Comment by qiugai** [comment]
mockup :)

![Image](https://user-images.githubusercontent.com/95944392/216420439-c1ec0ed5-f012-4de2-b1af-1de9628651c6.png)

**Comment by ZM009** [comment]
Planning phase completed; rough idea of what's desired so far
