### ISSUE TITLE
DC Motors - Finding Proper Resistance

### ISSUE THREAD

**Issue by nickkrisulevicz** [Salisbury-University/robot-weed-killer#33]
##  Expected Results

The robot should use the input voltage of the 12V rechargeable battery to evenly distribute its voltage and current among each TT motor with a breadboard. 

## Current Test Results

The robot currently moves too fast, and the 12V battery is currently sending too much current (amps) to the DC motors. This could result in them completely burning out. 

### Solution

Documentation has been found to find the resistance needed given the voltage and amperage:

To find voltage:
*  $V=I*R$ (V: Voltage, I: Current (measured in mA or A), and R: resistance (measured in ohms $\Omega$)

To find resistance given input voltage and current: 
* $R = \frac{V}{I}$

#### Current priority: Find the suggested current of the DC motors

[Current measurements of TT motors](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.adafruit.com%2Fproduct%2F3777%3Fgclid%3DCjwKCAiA3KefBhByEiwAi2LDHFsAweD2pzRRP57v9zoitfoc29EEQMsE5Yd-u_x1T0K0faNSF1b6yRoCa8MQAvD_BwE&data=05%7C01%7Cnkrisulevicz1%40gulls.salisbury.edu%7C042cc0c3570e49825c0e08db0dd3cca9%7C2472f1faf24f421badd7b01c4b49be07%7C0%7C0%7C638118975578246396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TxeWpMErZ%2FOrLRMt9dZ1kjutqLgnUYWcX4mdVDXh3ro%3D&reserved=0)

**Comment by ZM009** [comment]
Voltage was found to be a recommended 7.2 V per motor. 
Recommended current is 160mA (0.168 A)

Resistance found: $R=\frac{7.2}{0.168}$
$R=42.85\Omega\approx 43 \Omega$

**Comment by ZM009** [comment]
Robot wouldn't drive with issues, will be revisited later.
