### ISSUE TITLE
Inconsistent Access Point

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#34]
## Expected Behavior

The ESP32 Camera should consistently broadcast the wifi network to different devices when nothing is connected.

## Actual Behavior

The Access Point of the camera is very inconsistent when broadcasting the wifi, and sometimes disconnects while displaying video feed, shutting off any view of what the robot sees.

### Potential Solution

* Possibly add more power
* Give camera a dedicated circuit

**Comment by nickkrisulevicz** [comment]
A dedicated circuit was given to the camera, causing it to no longer draw insufficient power from the main circuit, this caused the camera to function completely and the access point now works consistently

**Comment by ZM009** [comment]
### Testing

#### Multiple tests were completed by Dane and Nick with the video feed. Supervised by Zach and Garrett. Solution Approved. 👍
