### ISSUE TITLE
Improvements and Reorganization of GitHub Wiki - Documentation (Ongoing)

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#41]
## Goal
----
* Must add detailed instructions under each header to describe project overview, installation instructions, etc. within the main wiki page
* Start to record better documentation of Flutter extensions, dependencies, and Arduino modules.
* Consolidate documentation in one area for any and all libraries used.
* Record and store all sprint updates in separate section. 
* Create biweekly client update sections

**Comment by nickkrisulevicz** [comment]
Will need to wait until all branches are merged before writing all READMEs or else chaos keeping track of all documentation could ensue.

**Comment by nickkrisulevicz** [comment]
The Wiki is more important to anyone who views the repository than individual READMEs in each directory
