### ISSUE TITLE
💡 Take Sonar Module Input with Arduino

### ISSUE THREAD

**Issue by nickkrisulevicz** [Salisbury-University/robot-weed-killer#46]
### Start Date

02/27/2023

### Reference Issues

#38 #35

### Summary

Need to write Arduino code to take the input from the HC-SR04 module. The purpose of this is to make sure that the autonomous control has input from the sonar equipment so that it can be used to make the robot stop when there is an object in its path during autonomous function.

### Basic Example

Feature will consist of Arduino code.

### Drawbacks

Need to troubleshoot any potential bugs in the Arduino code during implementation.

**Comment by nickkrisulevicz** [comment]
Sonar module has been troubleshot, wired up, and takes input as intended. Now, the autonomous code can be implemented as the necessary hardware is currently in place.

**Comment by qiugai** [comment]
Observed new sonar library implementation and test case results.
