### ISSUE TITLE
💡 Train Weed Detection Model on Weed Dataset

### ISSUE THREAD

**Issue by qiugai** [Salisbury-University/robot-weed-killer#48]
### Start Date

3/7/23

### Summary

We need to change from our generic yolov5 general object dataset, to a custom model using a dataset of weeds on sidewalks and pavements.

### Basic Example

Detect weeds not fridges and people and chairs

### Drawbacks

Training take long time :(

**Comment by qiugai** [comment]
Data is being trained on Roboflow, ~1000 images, **50% | 30% | 20%** | Train | Valid | Test split

**Comment by ZM009** [comment]
Experienced the results of the training yesterday. Holy moly

**Comment by ZM009** [comment]
Data training worked fine, model had some different results when training more.
