### ISSUE TITLE
💡 Setup MapBox API Credentials

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#49]
### Start Date

03/07/2023

### Implementation PR

_No Pull Requests Used as of now_

### Reference Issues

_No Issues Referenced_

### Summary

MapBox is an API used by OpenStreetMap. This is a general setup of any access tokens needed for eventual autonomous pathing using various algorithms like Dijkstra 's Shortest Path, etc. For now, basic setup is the primary goal which will include generating an authenticating key, secret keys for map manipulation, etc.

### Basic Example

With the setup of the API, this would allow for an interactive map to be created, eventually leading to a user able to choose a start and stop point for the laser robot, and implement any pathing algorithms used/designed for max efficiency. 

### Drawbacks

Possible Drawbacks Include:
* If request limit is surpassed, it will cost monthly per an additional amount of requests per month. (Very minimal chance)
* Current Robot Design:
     * May need a sort of GPS module installed; which has a moderate range of error.

**Comment by qiugai** [comment]
API Credentials have been added to the gradle files. Meeting with client to determine when to implement mapping
