### ISSUE TITLE
💡 Develop Autonomous Algorithm to Navigate Corners

### ISSUE THREAD

**Issue by nickkrisulevicz** [Salisbury-University/robot-weed-killer#51]
### Start Date

03/13/2023

### Reference Issues

#40 #35

### Summary

Basic implementation of the autonomous algorithm has been achieved. This was taken care of in issue #40. The current state of the algorithm results in undesirable behavior with the robot navigating when it is positioned in a corner. The objective of the resolution of this issue is to continue to develop the autonomous code to ensure that the robot can navigate out of corners.

### Basic Example

The resulting code from this feature will consist of Arduino code. The location of the files are /Control/sonar. The files are currently in branch: sonar_patrol. This will not be merged with main branch for the time being.

### Drawbacks

Potential drawbacks to this feature are time requirements and capabilities of the hardware. The motors can only be set to either HIGH or LOW, without precise modulation of speed. This can result in inconsistent turning duration, forward and reverse distance, as well as other complications while driving. The solution can be to carefully observe and test various values within the driving program.

**Comment by ZM009** [comment]
Sonar Patrol was modified, forgot to close.
