### ISSUE TITLE
🐛 Can't view camera stream on current server program

### ISSUE THREAD

**Issue by qiugai** [Salisbury-University/robot-weed-killer#55]
### Description

When trying to access the livestream at the ESP32 IP address, the yolov5 and OpenCV programs both time out, thus cannot run the weed detection model on them.

### Reproduction steps

```bash
1. Connect to ESP32 hotspot
2. Launch yolov5 or OpenCV with source of 'http://192.168.4.1'
```

**Comment by ZM009** [comment]
😭 😞 😢

**Comment by ZM009** [comment]
![IMG_5657](https://user-images.githubusercontent.com/50252234/229540174-05179a24-38c4-4121-99fc-cab387df22b3.JPG)

**Comment by ZM009** [comment]
The bug was fixed, camera can be used on server.
