### ISSUE TITLE
🛠 Modify and Print Final Chassis Design

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#58]
### Start Date

04/05/2023

### Reference Issues

#54 #51 

### Summary

The final design for the chassis will be printed and modified upon printing to add all necessary parts to the robot for further improvement of the autonomous algorithm.

## Improvements Explained
* Camera placement changed to prevent shake
* Move motor mounts for more freedom of design
* Used to further develop autonomous algorithm
* Integrated laser mount to prevent shake upon braking

**Comment by nickkrisulevicz** [comment]
Designed new chassis iteration. Calculated weight distribution included in new directory located in sonar_patrol branch.

**Comment by ZM009** [comment]
Chassis pieces printed in MakerLab
