### ISSUE TITLE
💡 Create and Implement Getters for Latitude and Longitude

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#59]
### Start Date

04/05/2023

### Reference Issues

#57 

### Summary

Private getter functions would be created to utilize the latlng package's features in order to grab latitude and longitude measurements of custom points when the user holds an area of the map down.

### Basic Example

* Can create possible start and end points for robot path planning
* Could be used to track gps coordinates

### Drawbacks

Coordinates could have a bigger window of error; could require further refinement of the getters.

**Comment by ZM009** [comment]
can use flutter_map's functionality to grab the latitude and longitude of a gps. Very high level implementation depending on the purpose.

**Comment by nickkrisulevicz** [comment]
flutter_map works with the current GPS module just fine?

**Comment by ZM009** [comment]
Yes. There's two libraries in flutter we can use to handle this: nmea, and latlong2. Latlong2 contains predefined types to contain the coordinates, while the nmea library is a parser that can be used to extract the given robot coordinates from the gps information sent by the arduino. These two can be tied in with flutter_map to reload the map's tiles and continually track the robot's location

**Comment by ZM009** [comment]
After implementation there's a possibility of giving a robot a start and end point for path planning, but that may not be implemented due to time constraints.

**Comment by ZM009** [comment]
No time left to learn nmea parsing
