### ISSUE TITLE
🐛 Screen Orientations Code Deprecated

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#62]
### Description

When attempting to run the debug (or build) version(s) of the application, flutter catches and throws an error related to overriding a Navigator class function. This is due to deprecated code, and will need either a migrated fixed or a workaround.

### Reproduction steps

```bash
1. Change branch to dynamic_orientations
2. Connect device to laptop
3. Use flutter run --no-sound-null-safety
4. Check logs from console
```

### Logs

```bash
'NavigatorObserverWithOrientation.didPop' ('void Function(Route<dynamic>, Route<dynamic>)') isn't a valid override of 'NavigatorObserver.didPop' ('void Function(Route<dynamic>, Route<dynamic>?)').dart(invalid_override)
```

**Comment by evHitch** [comment]
Found simple way to set preferred orientations on each respective page inside the initState() method.

**Comment by AdultVaccinationsLES** [comment]
respective page orientations set in initState() method.
