### ISSUE TITLE
🐛 Undefined Error for FlutterMap layers

### ISSUE THREAD

**Issue by ZM009** [Salisbury-University/robot-weed-killer#67]
### Description

When running the app in debug mode, the console logs an error relating to the layers list, marker options and tile layer options. 

### Reproduction steps

```bash
1. go to bt_controller:  robot-weed-killer/bt_controller
2. run command: ```flutter run --no-sound-null-safety``` (working on migration)
```

**Comment by ZM009** [comment]
Fixed; found out method i was using was deprecated when reading flutter_map docs. pubspec auto updated to latest version, and i refactored accordingly.

take a look @nickkrisulevicz thanks :)

<img width="966" alt="Screenshot 2023-04-15 at 9 40 13 PM" src="https://user-images.githubusercontent.com/50252234/232261570-576575c6-b717-40a3-9d23-e297cc09b230.png">

**Comment by nickkrisulevicz** [comment]
Looks good. Let me know if there is anything I can do to help if any future problems arise
