### ISSUE TITLE
💡 Finish Autonomous Operation - Hardware is Complete

### ISSUE THREAD

**Issue by nickkrisulevicz** [Salisbury-University/robot-weed-killer#68]
### Start Date

04/15/2023

### Reference Issues

#38 #21 #23 #35

### Summary

Now that hardware fixes and additions are complete, the next objective is to finish the autonomous driving algorithm for obstacle avoidance. More on object recognition and driving to follow.

### Basic Example

Deliverable product from this issue will be Arduino code in a .ino file

### Drawbacks

Will need to add object recognition and auto driving cooperation following resolution of this issue.

**Comment by ZM009** [comment]
Nice. 👨
