### ISSUE TITLE
💡 Arduino Code Manual / Auto Toggle

### ISSUE THREAD

**Issue by qiugai** [Salisbury-University/robot-weed-killer#71]
### Start Date

4/27/23

### Summary

need to switch between automatic and manual control arduino

### Basic Example

Press button, autonomous robot, press again, manual

### Drawbacks

Hard :(

**Comment by ZM009** [comment]
is this basically done

**Comment by qiugai** [comment]
Yes finished

**Comment by ZM009** [comment]
Good stuff.

Closed by most recent merge
