### ISSUE TITLE
🛠 Fix wiring for sonar sensors

### ISSUE THREAD

**Issue by nickkrisulevicz** [Salisbury-University/robot-weed-killer#72]
### Start Date

4/30/2023

### Summary

The sonar sensors were wired up to Vin which ranges from 7v to 12v. This caused the three sonar sensors to overheat and die. This caused the autonomous code to not work since input from the sonar sensors was not what it needed to be. The sonar sensors need to be replaced, and the wires need to be connected to 5v instead of Vin

### Basic Uses

This will affect the autonomous code's ability to run

**Comment by ZM009** [comment]
Sonars were replaced and are fully functional.
